[tox]
envlist = py311,py312,py313,coverage
requires = tox-uv>=1

[testenv]
extras = test
commands = pytest {posargs}

[testenv:coverage]
commands = pytest --cov=monetils --cov-report=term-missing {posargs}
